---
version: 0.5.12
slug: ezddns
name: EZ DDNS
description: >
  Easy Cloudflare DDNS updates for IPv6 and IPv4
url: https://github.com/TKtheDEV/EZDDNS
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
init: false

options:
  zoneId: null
  apiToken: null
  fqdn: null
  v4En: false
  prefixLength: 56
  refresh: 300
  legacy: false
  customEn: false
  records: []
schema:
  zoneId: str?
  apiToken: password
  fqdn: str?
  v4En: bool
  prefixLength: list(48|52|56|60|64)
  refresh: "int(20,)"
  legacy: bool
  customEn: bool
  records:
    - str
